### PR TITLE
Added Login

### PR DESCRIPTION
**Pull request by The-God-coder**
Added Login with mongodb.

### CODE REVIEW

**Comment by maitian352** [comment]
Cool!

**Comment by maitian352** [comment]
Is the Username and Password stored locally or globally?

**Comment by The-God-coder** [comment]
> Is the Username and Password stored locally or globally?

If you mean if its stored on a server or in a file its stored in a mongodb server that can legit be anywhere in the world

**Comment by maitian352** [comment]
Now this pull request is conflicting.

**Pull request merged**
